..\Output\Bin\WinVs2022Debug64\StaticLinkUtil.exe ..\Code\Engine\Core
..\Output\Bin\WinVs2022Debug64\StaticLinkUtil.exe ..\Code\Engine\Foundation
..\Output\Bin\WinVs2022Debug64\StaticLinkUtil.exe ..\Code\Engine\GameEngine
..\Output\Bin\WinVs2022Debug64\StaticLinkUtil.exe ..\Code\Engine\RendererCore
..\Output\Bin\WinVs2022Debug64\StaticLinkUtil.exe ..\Code\Engine\RendererVulkan
..\Output\Bin\WinVs2022Debug64\StaticLinkUtil.exe ..\Code\Engine\RendererCore
..\Output\Bin\WinVs2022Debug64\StaticLinkUtil.exe ..\Code\Engine\Texture
..\Output\Bin\WinVs2022Debug64\StaticLinkUtil.exe ..\Code\Engine\Utilities
..\Output\Bin\WinVs2022Debug64\StaticLinkUtil.exe ..\Code\UnitTests\TestFramework
..\Output\Bin\WinVs2022Debug64\StaticLinkUtil.exe ..\Code\EnginePlugins\InspectorPlugin